### ISSUE TITLE
Responsive styles

### ISSUE THREAD

**Issue by lynnandtonic** [AmpersandJS/ampersandjs.com#10]

**Comment by latentflip** [comment]
Gonna add this here, rather than a separate issue, but there seems to be an interaction between the max-width of the .docs container, and the percentage width of the nav/docs that's causing: on large screen sizes.

![Uploading Ampersand.js - Documentation 2014-06-20 13-48-18 2014-06-20 13-48-23.png . . .]()

**Comment by lynnandtonic** [comment]
I think responsive is pretty set. Closing this for now and we can put any bugs into other issues.
