### ISSUE TITLE
Ampersand modules need an example folder

### ISSUE THREAD

**Issue by alessioalex** [AmpersandJS/ampersandjs.com#145]
I like to run a basic example as fast as I can instead of reading through the documentation and looking at tests. I read about basic usage the readme file and then I want to run something. However most ampersand modules in this group don't have any.

Ex: compare https://github.com/AmpersandJS/ampersand-router to https://github.com/visionmedia/page.js/tree/master/examples

What do you guys think?

**Comment by lukekarrys** [comment]
Hey @alessioalex, we do have a global examples repo over here https://github.com/AmpersandJS/examples. So far that's the route we've decided to go instead of the examples directory inside of each individual module. If you have any specific example you'd like to see, it'd be best to open an issue or a PR over on that repo.

Also, installing the [ampersand cli tool](https://github.com/AmpersandJS/ampersand#the-ampersand-cli) (`npm install ampersand -g`) is a good way of generating a sample app to get started quickly.
