### ISSUE TITLE
When viewing a multi-part guide, a prev/next control would be helpful

### ISSUE THREAD

**Issue by wraithgar** [AmpersandJS/ampersandjs.com#154]
As per: https://twitter.com/LewisCowper/status/599315495205138432

**Comment by cdaringe** [comment]
dead link

**Comment by wraithgar** [comment]
Apparently the tweet was deleted, it linked here http://ampersandjs.com/learn/quick-start-guide

Not sure if that means it's a non-issue or what but a person smarter than me about UI could probably weigh in here.

**Comment by lewiscowper** [comment]
So I clicked through to the quick start guide, and assumed that I was missing something because the guide just stopped. I tweeted, then realised that that was the full extent of the quick start guide.

Once I realised that, I deleted the tweet.

The general multi-part guide prev/next is still valid, but the specific guide I was looking at wasn't a multi-part guide, I just missed the point of the quick start guide.
